const data = [
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers One",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Three",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Two",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Four",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Five",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Six",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers One",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Three",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Two",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Four",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Five",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Six",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers One",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Three",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Two",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Four",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Five",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Six",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers One",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Three",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Two",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Four",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Five",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Six",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers One",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Three",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Two",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Four",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Five",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Six",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers One",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Three",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Two",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Four",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Five",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
    {
      data: {
        faceboo: "",
        follower: "168,723",
        instagra: "",
        monthlylisten: "610,949",
        name: "The Searchers Six",
        twitte: "",
        url: "https://open.spotify.com/artist/4QmkLL9JOqM9dusHS1Hghe",
        wikipedi: "",
      },
      platfor: "spotify_artist",
      scrapper_nam: "username",
      searc: "search",
      timestam: "2022-11-21 14:22",
    },
  ];
  
  export default data;
  